# Form implementation generated from reading ui file 'template.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 640)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/robo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(0.95)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.txt_chat = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_chat.setObjectName("txt_chat")
        self.gridLayout.addWidget(self.txt_chat, 2, 1, 5, 1)
        self.bt_usar_mic = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_usar_mic.setObjectName("bt_usar_mic")
        self.gridLayout.addWidget(self.bt_usar_mic, 6, 2, 1, 1)
        self.bt_enviar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_enviar.setObjectName("bt_enviar")
        self.gridLayout.addWidget(self.bt_enviar, 5, 2, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(150, 200))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("assets/robo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sueli artificial Inteligence"))
        self.txt_chat.setPlaceholderText(_translate("MainWindow", "Pergunte qualquer coisa..."))
        self.bt_usar_mic.setText(_translate("MainWindow", "Usar Microfone"))
        self.bt_enviar.setText(_translate("MainWindow", "Enviar"))
